//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageList_eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageList_eng() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource.ErrorMessageList_eng", typeof(ErrorMessageList_eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to initialize communication.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C001 {
            get {
                return ResourceManager.GetString("C001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to send logs to remote location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C002 {
            get {
                return ResourceManager.GetString("C002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an error in your ID or password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C003 {
            get {
                return ResourceManager.GetString("C003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to database.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C004 {
            get {
                return ResourceManager.GetString("C004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid Gerber file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G001 {
            get {
                return ResourceManager.GetString("G001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is corrupted or too large, so the viewer cannot open this photo.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid teaching file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect log retention days input.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L001 {
            get {
                return ResourceManager.GetString("L001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to initialize directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid Model file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid Sheet file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid Strip file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The entered value exceeds the allowed range.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find the strip information. 
        ///Cannot edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sheet information could not be found. 
        ///It cannot be modified.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No model information found. 
        ///Cannot be modified.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The currently selected model cannot be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M009 {
            get {
                return ResourceManager.GetString("M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to PLC.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC001 {
            get {
                return ResourceManager.GetString("MC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to initialize counter.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC002 {
            get {
                return ResourceManager.GetString("MC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to light.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC003 {
            get {
                return ResourceManager.GetString("MC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POP connection failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC004 {
            get {
                return ResourceManager.GetString("MC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to connect to SERVER.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC005 {
            get {
                return ResourceManager.GetString("MC005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is currently no equipment information in the IGS Server status monitoring table. Please request equipment registration in the base technology.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC006 {
            get {
                return ResourceManager.GetString("MC006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to report start.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC007 {
            get {
                return ResourceManager.GetString("MC007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start reporting due to server error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC008 {
            get {
                return ResourceManager.GetString("MC008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto-start reporting is disabled due to server failure.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC009 {
            get {
                return ResourceManager.GetString("MC009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POP outage report failure: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC010 {
            get {
                return ResourceManager.GetString("MC010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access by unauthorized users.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC011 {
            get {
                return ResourceManager.GetString("MC011", resourceCulture);
            }
        }
        
        /// <summary>
        ///    light is OFF. Please re-run the program and proceed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC012 {
            get {
                return ResourceManager.GetString("MC012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic inspection terminated with error:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC013 {
            get {
                return ResourceManager.GetString("MC013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify the connection has been lost.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MC014 {
            get {
                return ResourceManager.GetString("MC014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save section data to DB. 
        ///Please check the connection status and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to send section data.
        ///Please check the connection status with Vision and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to acquire section image. 
        ///Please check the connection status with Vision and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to acquire video. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The connection to Vision has been lost. 
        ///If the problem persists, please restart Vision.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Teaching Data you are trying to read is different from the currently selected model.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT006 {
            get {
                return ResourceManager.GetString("MT006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Teaching Data you are trying to read is larger than the currently registered video.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT007 {
            get {
                return ResourceManager.GetString("MT007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are Sections with the same starting position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT008 {
            get {
                return ResourceManager.GetString("MT008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a Section occupying the same location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT009 {
            get {
                return ResourceManager.GetString("MT009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R001 {
            get {
                return ResourceManager.GetString("R001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select top or bottom.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R002 {
            get {
                return ResourceManager.GetString("R002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a color.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R003 {
            get {
                return ResourceManager.GetString("R003", resourceCulture);
            }
        }
    }
}
