//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessageList_eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessageList_eng() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource.InformationMessageList_eng", typeof(InformationMessageList_eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   It has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C001 {
            get {
                return ResourceManager.GetString("C001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It has been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C002 {
            get {
                return ResourceManager.GetString("C002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C003 {
            get {
                return ResourceManager.GetString("C003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the equipment name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for duplicate equipment names.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected machine?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name has already been registered. Please enter it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is an available name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only up to 8 Gerber layers can be registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G001 {
            get {
                return ResourceManager.GetString("G001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gerber layer is not registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G002 {
            get {
                return ResourceManager.GetString("G002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The same operation is currently being performed.
        ///Please try again later.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string G003 {
            get {
                return ResourceManager.GetString("G003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the name of the inspector.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for duplicate inspection names.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected items?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name has already been registered. Please enter it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is an available name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;&lt;XMLConfigSettings&gt;&lt;/XMLConfigSettings&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IDS_DEFAULT_XML {
            get {
                return ResourceManager.GetString("IDS_DEFAULT_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a model.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IS001 {
            get {
                return ResourceManager.GetString("IS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After loading the image, you can draw on it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IV001 {
            get {
                return ResourceManager.GetString("IV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save logs to the local file system.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L001 {
            get {
                return ResourceManager.GetString("L001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Does not store logs on the local file system.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string L002 {
            get {
                return ResourceManager.GetString("L002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please give the new strip a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no registered sheet information. 
        ///Please create a new one.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no registered strip information. 
        ///Please create a new one.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet information has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are sheets with duplicate names. 
        ///Please change the name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strip information has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are duplicate strips with the same name. 
        ///Please change the name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected items?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M008 {
            get {
                return ResourceManager.GetString("M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sheet information has been modified.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M009 {
            get {
                return ResourceManager.GetString("M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strip information has been corrected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M010 {
            get {
                return ResourceManager.GetString("M010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please give the new sheet a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M011 {
            get {
                return ResourceManager.GetString("M011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please give the new model a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M012 {
            get {
                return ResourceManager.GetString("M012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to cancel your input?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M013 {
            get {
                return ResourceManager.GetString("M013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to exit without saving changes?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M014 {
            get {
                return ResourceManager.GetString("M014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are changes.
        ///Do you want to save and navigate to another page?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M015 {
            get {
                return ResourceManager.GetString("M015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a model with a duplicate name. 
        ///Please change the name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M016 {
            get {
                return ResourceManager.GetString("M016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model information has been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M017 {
            get {
                return ResourceManager.GetString("M017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model information has been modified.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M018 {
            get {
                return ResourceManager.GetString("M018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please fill in all fields.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M019 {
            get {
                return ResourceManager.GetString("M019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following characters cannot be used:
        ///
        ///\ / : * ? &quot; &lt; &gt; |
        ///
        ///The following system reserved words cannot be used.
        ///
        ///&quot;CON&quot;, &quot;PRN&quot;, &quot;AUX&quot;, &quot;NUL&quot;
        ///&quot;COM1&quot;, &quot;COM2&quot;, &quot;COM3&quot;, &quot;COM4&quot;, &quot;COM5&quot;
        ///&quot;COM6&quot;, &quot;COM7&quot;, &quot;COM8&quot;, &quot;COM9&quot;
        ///&quot;LPT1&quot;, &quot;LPT2&quot;, &quot;LPT3&quot;, &quot;LPT4&quot;, &quot;LPT5&quot;
        ///&quot;LPT6&quot;, &quot;LPT7&quot;, &quot;LPT8&quot;, &quot;LPT9&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M020 {
            get {
                return ResourceManager.GetString("M020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not be used  &quot;.&quot; or &quot;..&quot; as a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M021 {
            get {
                return ResourceManager.GetString("M021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please create or select a group to which the model will belong.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M022 {
            get {
                return ResourceManager.GetString("M022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the model you wish to modify.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M023 {
            get {
                return ResourceManager.GetString("M023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the model you wish to delete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M024 {
            get {
                return ResourceManager.GetString("M024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the category you wish to edit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M025 {
            get {
                return ResourceManager.GetString("M025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the category you wish to delete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M026 {
            get {
                return ResourceManager.GetString("M026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The category has been created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M027 {
            get {
                return ResourceManager.GetString("M027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The category name has been changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M028 {
            get {
                return ResourceManager.GetString("M028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected category has been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M029 {
            get {
                return ResourceManager.GetString("M029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product width must be larger than 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M030 {
            get {
                return ResourceManager.GetString("M030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product length must be larger than 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M031 {
            get {
                return ResourceManager.GetString("M031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The correction value must be a value greater than or equal to 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M032 {
            get {
                return ResourceManager.GetString("M032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The compensation value cannot exceed the size of the product.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M033 {
            get {
                return ResourceManager.GetString("M033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block must be at least 1. 
        ///(If it is a one-map type, specify 1.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M034 {
            get {
                return ResourceManager.GetString("M034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When the number of blocks is 1, the pitch value is saved by applying it in the same way as the product size.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M035 {
            get {
                return ResourceManager.GetString("M035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Pitch value of the Block must be greater than 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M036 {
            get {
                return ResourceManager.GetString("M036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The X-axis pitch value of the block cannot exceed the length of the product.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M037 {
            get {
                return ResourceManager.GetString("M037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Y-axis pitch value of the Block cannot exceed the length of the product.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M038 {
            get {
                return ResourceManager.GetString("M038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit must be at least 1.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M039 {
            get {
                return ResourceManager.GetString("M039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of Unit X-axis must be a multiple of the number of Block X-axis.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M040 {
            get {
                return ResourceManager.GetString("M040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of Unit Y-axis must be a multiple of the number of Block Y-axis.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M041 {
            get {
                return ResourceManager.GetString("M041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Pitch value of Unit must be greater than 0.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M043 {
            get {
                return ResourceManager.GetString("M043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Unit&apos;s X-axis Pitch value cannot exceed the length of the product.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M044 {
            get {
                return ResourceManager.GetString("M044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Unit&apos;s Y-axis Pitch value cannot exceed the length of the product.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M045 {
            get {
                return ResourceManager.GetString("M045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement of X-axis Unit exceeds the Block X-axis Pitch length. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M046 {
            get {
                return ResourceManager.GetString("M046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement of Y-axis Unit exceeds the Block Y-axis Pitch length. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M047 {
            get {
                return ResourceManager.GetString("M047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The array of X-axis Units exceeds the length of the product. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M048 {
            get {
                return ResourceManager.GetString("M048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement of the Y-axis Unit exceeds the width of the product. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M049 {
            get {
                return ResourceManager.GetString("M049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement of X-axis Blocks exceeds the length of the product. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M050 {
            get {
                return ResourceManager.GetString("M050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement of Y-axis Blocks exceeds the width of the product. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M051 {
            get {
                return ResourceManager.GetString("M051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M052 {
            get {
                return ResourceManager.GetString("M052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create category. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M053 {
            get {
                return ResourceManager.GetString("M053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to edit category. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M054 {
            get {
                return ResourceManager.GetString("M054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete category. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M055 {
            get {
                return ResourceManager.GetString("M055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model creation failed. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M056 {
            get {
                return ResourceManager.GetString("M056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model modification failed. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M057 {
            get {
                return ResourceManager.GetString("M057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete model. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M058 {
            get {
                return ResourceManager.GetString("M058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected model has been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M059 {
            get {
                return ResourceManager.GetString("M059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The currently selected model cannot be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M060 {
            get {
                return ResourceManager.GetString("M060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The group to which the currently selected model belongs cannot be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M061 {
            get {
                return ResourceManager.GetString("M061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;\ / : * ? &apos; &quot; &lt; &gt; |&apos; cannot be used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M062 {
            get {
                return ResourceManager.GetString("M062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System reserved words can not be used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M063 {
            get {
                return ResourceManager.GetString("M063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of Block columns cannot exceed the number of Unit columns.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M064 {
            get {
                return ResourceManager.GetString("M064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of Block rows cannot exceed the number of Unit rows.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M065 {
            get {
                return ResourceManager.GetString("M065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a model.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M066 {
            get {
                return ResourceManager.GetString("M066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a lot.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M067 {
            get {
                return ResourceManager.GetString("M067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product length must be less than 300.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M068 {
            get {
                return ResourceManager.GetString("M068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product width must be less than 150.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M069 {
            get {
                return ResourceManager.GetString("M069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Units must be greater than or equal to (Unit X number X Unit Y number).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M070 {
            get {
                return ResourceManager.GetString("M070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accessible to administrators and above.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M071 {
            get {
                return ResourceManager.GetString("M071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M072 {
            get {
                return ResourceManager.GetString("M072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No more Local Aligns can be created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M073 {
            get {
                return ResourceManager.GetString("M073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected {0} ROIs?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M074 {
            get {
                return ResourceManager.GetString("M074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the entire ROI?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M075 {
            get {
                return ResourceManager.GetString("M075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the entire section ROI?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M076 {
            get {
                return ResourceManager.GetString("M076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The section size has changed. Do you want to apply it? 
        ///(Please make sure the ROI inside the section has changed correctly.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M077 {
            get {
                return ResourceManager.GetString("M077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are incorrectly entered values. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M078 {
            get {
                return ResourceManager.GetString("M078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The lower threshold value cannot exceed the upper threshold value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M079 {
            get {
                return ResourceManager.GetString("M079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The minimum lead line width cannot exceed the maximum lead line width.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M080 {
            get {
                return ResourceManager.GetString("M080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The overall Mask lower bound value cannot exceed the overall Mask upper bound value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M081 {
            get {
                return ResourceManager.GetString("M081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Shape Mask lower bound value cannot exceed the Shape Mask upper bound value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M082 {
            get {
                return ResourceManager.GetString("M082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The detection size is set to 0.\n Please fix it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M083 {
            get {
                return ResourceManager.GetString("M083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous automatic check terminated unstably. \nPlease re-run the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M084 {
            get {
                return ResourceManager.GetString("M084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Verify error has occurred. Please check the IP settings of your Verify PC.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M085 {
            get {
                return ResourceManager.GetString("M085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Verify error occurred due to a DB storage error or image transmission error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M086 {
            get {
                return ResourceManager.GetString("M086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No results received from Vision.\nPlease check Vision status and resume automatic inspection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M087 {
            get {
                return ResourceManager.GetString("M087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic inspection has been forcibly terminated.\nPlease restore to the origin and start again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string M088 {
            get {
                return ResourceManager.GetString("M088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no registered models. 
        ///Please create model information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROI cannot exceed 30 pixels in width or height.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select Unhide ROI and then perform the task.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only for the entire video Section Type, you can read the video from the file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The video has been saved. The saved video will be used as a reference image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the model you wish to teach.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the image. Please try again later.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT006 {
            get {
                return ResourceManager.GetString("MT006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please create a section area.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT007 {
            get {
                return ResourceManager.GetString("MT007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are Unit areas that are not set to repeat. 
        ///Please proceed with the repeat settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT008 {
            get {
                return ResourceManager.GetString("MT008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After registering the image, Please open the Teaching file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT009 {
            get {
                return ResourceManager.GetString("MT009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The section image has been saved. The saved image will be used as the reference image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT010 {
            get {
                return ResourceManager.GetString("MT010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reference image has been registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT011 {
            get {
                return ResourceManager.GetString("MT011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[TOP1] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT020 {
            get {
                return ResourceManager.GetString("MT020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[TOP2] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT021 {
            get {
                return ResourceManager.GetString("MT021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[BOT1] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT022 {
            get {
                return ResourceManager.GetString("MT022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[BOT2] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT023 {
            get {
                return ResourceManager.GetString("MT023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[TRANS1] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT024 {
            get {
                return ResourceManager.GetString("MT024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[TRANS2] has no sections created.\nPlease set up the sections.&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT025 {
            get {
                return ResourceManager.GetString("MT025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to send vision information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT026 {
            get {
                return ResourceManager.GetString("MT026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an inspection area outside the section.\n과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT027 {
            get {
                return ResourceManager.GetString("MT027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual check failed.\n과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT028 {
            get {
                return ResourceManager.GetString("MT028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial manual inspection failed.\n과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT029 {
            get {
                return ResourceManager.GetString("MT029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to acquire image.\n과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT030 {
            get {
                return ResourceManager.GetString("MT030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the Section for which you want to change the reference image.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT031 {
            get {
                return ResourceManager.GetString("MT031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a model.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT032 {
            get {
                return ResourceManager.GetString("MT032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data restoration has been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT033 {
            get {
                return ResourceManager.GetString("MT033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data matching the current model was found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MT034 {
            get {
                return ResourceManager.GetString("MT034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a defect name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N001 {
            get {
                return ResourceManager.GetString("N001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for duplicate defect names.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N002 {
            get {
                return ResourceManager.GetString("N002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the selected defect information?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N003 {
            get {
                return ResourceManager.GetString("N003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate name. Please enter again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string N004 {
            get {
                return ResourceManager.GetString("N004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the NG name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R001 {
            get {
                return ResourceManager.GetString("R001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for duplicate NG names.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R002 {
            get {
                return ResourceManager.GetString("R002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the selected NG information?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R003 {
            get {
                return ResourceManager.GetString("R003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name has already been registered. Please enter it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R004 {
            get {
                return ResourceManager.GetString("R004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the Strip NG rate.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R005 {
            get {
                return ResourceManager.GetString("R005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the Unit NG Rate.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R006 {
            get {
                return ResourceManager.GetString("R006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R007 {
            get {
                return ResourceManager.GetString("R007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not a valid date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R008 {
            get {
                return ResourceManager.GetString("R008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image will also be deleted. Do you want to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string R009 {
            get {
                return ResourceManager.GetString("R009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t want to save defect images?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The range value is incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your ID.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U001 {
            get {
                return ResourceManager.GetString("U001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U002 {
            get {
                return ResourceManager.GetString("U002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U003 {
            get {
                return ResourceManager.GetString("U003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check for ID duplication.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U004 {
            get {
                return ResourceManager.GetString("U004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password and password confirmation do not match.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U005 {
            get {
                return ResourceManager.GetString("U005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your password correctly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U006 {
            get {
                return ResourceManager.GetString("U006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected items?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U007 {
            get {
                return ResourceManager.GetString("U007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your password confirmation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U008 {
            get {
                return ResourceManager.GetString("U008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password and password confirmation do not match.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U009 {
            get {
                return ResourceManager.GetString("U009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This ID has already been registered. Please enter it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U010 {
            get {
                return ResourceManager.GetString("U010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This ID is available for use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string U011 {
            get {
                return ResourceManager.GetString("U011", resourceCulture);
            }
        }
    }
}
