using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;

// 2012.04.09 suoow2.

namespace Common.Drawing
{
    public class PropertiesGraphicsGuideLine : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;
        
        private Margin outerMargin;
        private Margin innerMargin;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsGuideLine()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
            System.Diagnostics.Debug.WriteLine("PropertiesGraphicsGuideLine 기본 생성자 호출, 아무일도 하지 않는다.");
        }

        public PropertiesGraphicsGuideLine(GraphicsGuideLine guideLine)
        {
            if (guideLine == null)
            {
                throw new ArgumentNullException("guideLine");
            }

            this.left = guideLine.Left;
            this.top = guideLine.Top;
            this.right = guideLine.Right;
            this.bottom = guideLine.Bottom;
            this.lineWidth = guideLine.LineWidth;
            this.regionType = guideLine.RegionType;
            this.objectColor = guideLine.ObjectColor;
            this.actualScale = guideLine.ActualScale;
            this.Id = guideLine.ID;
            this.selected = guideLine.IsSelected;
            this.caption = guideLine.Caption;
            this.outerMargin = guideLine.OuterMargin;
            this.innerMargin = guideLine.InnerMargin;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsGuideLine b = new GraphicsGuideLine(left, top, right, bottom, lineWidth, objectColor, actualScale, outerMargin, innerMargin);

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get
            {
                return Id;
            }
            set
            {
                Id = value;
            }
        }

        public double Left
        {
            get
            {
                return left;
            }
            set
            {
                left = value;
            }
        }

        public double Top
        {
            get
            {
                return top;
            }
            set
            {
                top = value;
            }
        }

        public double Right
        {
            get
            {
                return right;
            }
            set
            {
                right = value;
            }
        }

        public double Bottom
        {
            get
            {
                return bottom;
            }
            set
            {
                bottom = value;
            }
        }

        public GraphicsRegionType RegionType
        {
            get
            {
                return regionType;
            }
            set
            {
                regionType = value;
            }

        }

        public Color ObjectColor
        {
            get
            {
                return objectColor;
            }
            set
            {
                objectColor = value;
            }
        }

        public string Caption
        {
            get
            {
                return caption;
            }
            set
            {
                caption = value;
            }
        }

        [XmlElement(ElementName = "GuideLine1")]
        public Margin OuterMargin
        {
            get
            {
                return outerMargin;
            }
            set
            {
                outerMargin = value;
            }
        }

        [XmlElement(ElementName = "GuideLine2")]
        public Margin InnerMargin
        {
            get
            {
                return innerMargin;
            }
            set
            {
                innerMargin = value;
            }
        }
        #endregion Properties
    }

    public class PropertiesGraphicsTapeLoaction : PropertiesGraphicsBase
    {
        private double left;
        private double top;
        private double right;
        private double bottom;

        private double location;
        private double margin;
        private int direction;

        private double posX;
        private double posY;

        #region Ctor.
        // For XmlSerializer
        public PropertiesGraphicsTapeLoaction()
        {
            // XML로의 저장을 위해 기본 생성자가 필요하다.
            System.Diagnostics.Debug.WriteLine("PropertiesGraphicsGuideLine 기본 생성자 호출, 아무일도 하지 않는다.");
        }

        public PropertiesGraphicsTapeLoaction(GraphicsTapeLocation tape)
        {
            if (tape == null)
            {
                throw new ArgumentNullException("tapeLoaction");
            }

            this.left = tape.Left;
            this.top = tape.Top;
            this.right = tape.Right;
            this.bottom = tape.Bottom;
            this.lineWidth = tape.LineWidth;
            this.regionType = tape.RegionType;
            this.objectColor = tape.ObjectColor;
            this.actualScale = tape.ActualScale;
            this.Id = tape.ID;
            this.selected = tape.IsSelected;
            this.caption = tape.Caption;
            this.location = tape.Location;
            this.margin = tape.TapeMargin;
            this.direction = tape.Direction;
            this.posX = tape.PosX;
            this.posY = tape.PosY;
        }
        #endregion

        public override GraphicsBase CreateGraphics()
        {
            lineWidth = 2; // Default thickness.

            actualScale = (actualScale > 0) ? actualScale : 1.0;
            GraphicsTapeLocation b = new GraphicsTapeLocation(direction, posX, posY, lineWidth, objectColor, actualScale, location, margin);

            // GraphicsBase contains new ID generated by constructor.
            // This is OK if this instance is loaded from XML file.
            // But if this instance is part of commands history,
            // it contains ID which should be set in GraphicsBase.
            // This rule is applied to all SerializedGraphicsBase-derived
            // classes.
            if (this.Id != 0)       // from command history, not from file
            {
                b.ID = this.Id;
                b.IsSelected = this.selected;
            }

            return b;
        }

        #region Properties
        public int ID
        {
            get
            {
                return Id;
            }
            set
            {
                Id = value;
            }
        }

        public double Left
        {
            get
            {
                return left;
            }
            set
            {
                left = value;
            }
        }

        public double Top
        {
            get
            {
                return top;
            }
            set
            {
                top = value;
            }
        }

        public double Right
        {
            get
            {
                return right;
            }
            set
            {
                right = value;
            }
        }

        public double Bottom
        {
            get
            {
                return bottom;
            }
            set
            {
                bottom = value;
            }
        }

        public GraphicsRegionType RegionType
        {
            get
            {
                return regionType;
            }
            set
            {
                regionType = value;
            }

        }

        public Color ObjectColor
        {
            get
            {
                return objectColor;
            }
            set
            {
                objectColor = value;
            }
        }

        public string Caption
        {
            get
            {
                return caption;
            }
            set
            {
                caption = value;
            }
        }

        [XmlElement(ElementName = "Direction")]
        public int Direction
        {
            get
            {
                return direction;
            }
            set
            {
                direction = value;
            }
        }

        [XmlElement(ElementName = "PositionX")]
        public double PosX
        {
            get
            {
                return posX;
            }
            set
            {
                posX = value;
            }
        }
        [XmlElement(ElementName = "PostionnY")]
        public double PosY
        {
            get
            {
                return posY;
            }
            set
            {
                posY = value;
            }
        }

        [XmlElement(ElementName = "TapeMargin")]
        public double TapeMargin
        {
            get
            {
                return margin;
            }
            set
            {
                margin = value;
            }
        }

        [XmlElement(ElementName = "Location")]
        public double Location
        {
            get
            {
                return location;
            }
            set
            {
                location = value;
            }
        }
        #endregion Properties
    }
}
